-- Create table for Interior Calculator lead collection
CREATE TABLE IF NOT EXISTS interior_calculator_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  bhk TEXT NOT NULL,
  package_tier TEXT NOT NULL,
  carpet_area NUMERIC,
  renovation BOOLEAN,
  customization TEXT,
  estimated_min NUMERIC,
  estimated_max NUMERIC,
  source_page TEXT DEFAULT '/interiors',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add index for phone and created_at
CREATE INDEX IF NOT EXISTS idx_interior_calculator_leads_phone ON interior_calculator_leads(phone);
CREATE INDEX IF NOT EXISTS idx_interior_calculator_leads_created_at ON interior_calculator_leads(created_at);

-- Add RLS (Row Level Security)
ALTER TABLE interior_calculator_leads ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert leads
CREATE POLICY "Anyone can insert interior calculator leads" ON interior_calculator_leads
  FOR INSERT WITH CHECK (true);

-- Allow service role to read all leads
CREATE POLICY "Service role can read all leads" ON interior_calculator_leads
  FOR SELECT USING (auth.role() = 'service_role');
