-- Create table for Gudi Padwa lead collection
CREATE TABLE IF NOT EXISTS gudi_padwa_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  property_type TEXT NOT NULL,
  source_page TEXT NOT NULL DEFAULT '/design-studio',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_gudi_padwa_leads_created_at ON gudi_padwa_leads(created_at);
CREATE INDEX IF NOT EXISTS idx_gudi_padwa_leads_phone ON gudi_padwa_leads(phone);

-- Add RLS (Row Level Security)
ALTER TABLE gudi_padwa_leads ENABLE ROW LEVEL SECURITY;

-- Allow anyone (including anonymous users) to insert leads
CREATE POLICY "Anyone can insert gudi padwa leads" ON gudi_padwa_leads
  FOR INSERT WITH CHECK (true);

-- Allow service role to read all leads
CREATE POLICY "Service role can read all leads" ON gudi_padwa_leads
  FOR SELECT USING (auth.role() = 'service_role');

-- Allow anonymous users to read their own inserted data (optional)
CREATE POLICY "Users can read their own leads" ON gudi_padwa_leads
  FOR SELECT USING (true);

-- Add updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_gudi_padwa_leads_updated_at 
  BEFORE UPDATE ON gudi_padwa_leads 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
