-- Analytics Schema for Patronage Realtor
-- Create user_events table to track all user interactions
CREATE TABLE IF NOT EXISTS user_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  event_name TEXT NOT NULL,
  page_path TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create session_summaries table for AI-generated insights
CREATE TABLE IF NOT EXISTS session_summaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE,
  summary JSONB NOT NULL,
  intent_score INTEGER DEFAULT 0 CHECK (intent_score >= 0 AND intent_score <= 100),
  recommended_action TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_user_events_session_id ON user_events(session_id);
CREATE INDEX IF NOT EXISTS idx_user_events_created_at ON user_events(created_at);
CREATE INDEX IF NOT EXISTS idx_user_events_event_name ON user_events(event_name);
CREATE INDEX IF NOT EXISTS idx_session_summaries_session_id ON session_summaries(session_id);
CREATE INDEX IF NOT EXISTS idx_session_summaries_intent_score ON session_summaries(intent_score);

-- Add RLS policies
ALTER TABLE user_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_summaries ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert events (anon key from edge function)
CREATE POLICY "Allow insert user events" ON user_events
  FOR INSERT WITH CHECK (true);

-- Allow service role to insert events
CREATE POLICY "Service role can insert events" ON user_events
  FOR INSERT WITH CHECK (auth.role() = 'service_role');

-- Allow service role to read all events
CREATE POLICY "Service role can read user events" ON user_events
  FOR SELECT USING (auth.role() = 'service_role');

-- Allow service role to manage summaries
CREATE POLICY "Service role can manage session summaries" ON session_summaries
  FOR ALL USING (auth.role() = 'service_role');

-- Add updated_at trigger for session_summaries
CREATE OR REPLACE FUNCTION update_session_summaries_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_session_summaries_updated_at 
  BEFORE UPDATE ON session_summaries 
  FOR EACH ROW EXECUTE FUNCTION update_session_summaries_updated_at();
